services:
  - type: web
    name: ai-notes-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SUPABASE_DATABASE_URL
        value: postgresql://postgres.hctjruwhcswtxjerldxu:4edcvfr!78tgbnhy@aws-0-us-west-2.pooler.supabase.com:5432/postgres
      - key: SILICONFLOW_API_KEY
        value: sk-qvvudxjlrzqrroosrbwjpgthblljrvuqsisemesysgilxokc